import type { NextConfig } from 'next';
import { execSync } from 'child_process';
import { readFileSync } from 'fs';

// Safe: hardcoded command, no user input — runs at build time only
const gitHash = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();

// Build version generated by prebuild script
const buildVersion = (() => {
  try { return JSON.parse(readFileSync('build-version.json', 'utf8')).v; }
  catch { return 'unknown'; }
})();

const nextConfig: NextConfig = {
  // node-pty is native and must not be bundled by webpack
  serverExternalPackages: ['node-pty'],
  env: {
    NEXT_PUBLIC_GIT_HASH: gitHash,
    NEXT_PUBLIC_BUILD_VERSION: buildVersion,
  },
};

export default nextConfig;
