import { browser, $, expect } from '@wdio/globals';
import {
  navigateToSession, tapButton, getTmuxPaneContent,
  isTmuxInCopyMode, exitTmuxCopyMode,
} from '../helpers/terminal.js';

describe('Scroll FABs', () => {
  beforeEach(async () => {
    await navigateToSession();
    exitTmuxCopyMode();
  });

  it('should show scroll FABs on mobile', async () => {
    const up = await $('button[title="Scroll up (tmux)"]');
    const down = await $('button[title="Scroll down (tmux)"]');
    await expect(up).toExist();
    await expect(down).toExist();
  });

  it('should enter tmux copy mode on scroll-up tap', async () => {
    expect(isTmuxInCopyMode()).toBe(false);

    await tapButton('Scroll up (tmux)');
    await browser.pause(1500);

    // The scroll-up FAB sends tmux prefix + [ to enter copy mode, then PgUp
    expect(isTmuxInCopyMode()).toBe(true);

    // With scrollback generated by /help in onPrepare, we should see
    // different content than the current prompt screen
    const pane = getTmuxPaneContent();
    expect(pane.trim().length).toBeGreaterThan(0);
  });

  it('should scroll down and exit copy mode', async () => {
    // Enter copy mode first
    await tapButton('Scroll up (tmux)');
    await browser.pause(1500);
    expect(isTmuxInCopyMode()).toBe(true);

    // Scroll down — may exit copy mode if we reach the bottom
    await tapButton('Scroll down (tmux)');
    await browser.pause(500);

    // Pane should still be alive
    const pane = getTmuxPaneContent();
    expect(pane.trim().length).toBeGreaterThan(0);
  });
});
