import { browser, expect } from '@wdio/globals';
import {
  navigateToSession, swipeOnTerminal, getTmuxPaneContent,
  isTmuxInCopyMode, exitTmuxCopyMode,
} from '../helpers/terminal.js';

describe('Touch Scroll', () => {
  beforeEach(async () => {
    await navigateToSession();
    exitTmuxCopyMode();
  });

  it('should enter copy mode on swipe down', async () => {
    expect(isTmuxInCopyMode()).toBe(false);

    // Swipe down (finger moves down) — triggers SGR mouse wheel scroll-up in tmux.
    // tmux with mouse on auto-enters copy mode on scroll up.
    // Scrollback content generated by /help in onPrepare ensures there's
    // history to scroll into.
    await swipeOnTerminal(200);
    await browser.pause(1500);

    expect(isTmuxInCopyMode()).toBe(true);
  });

  it('should respond to swipe up after swipe down', async () => {
    // First swipe down to enter copy mode
    await swipeOnTerminal(200);
    await browser.pause(1500);

    // Swipe up (finger moves up) — scrolls down in tmux
    await swipeOnTerminal(-200);
    await browser.pause(500);

    // Pane should still be alive with content
    const pane = getTmuxPaneContent();
    expect(pane.trim().length).toBeGreaterThan(0);
  });
});
